name: rygo6
favicon: null
layout_spectrum: 0.314017275813967
typography_spectrum: 0.7161244454327971
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.5538273989222944
  lightness: 0.5310257598757744
  saturation: 0.4631240488961339
  rhythmicContrast: 0.19080622540786862
purpose: []
